name: eb-node-deploy-action

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
    
    - run: zip -r deploy.zip * -x "**node_modules**"
    
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
      
    - name: Beanstalk Deploy for app
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_REACT_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_REACT_KEY}}
        application_name: "ec2-node"
        environment_name: "ec2-node-dev"
        region: "us-east-1"
        version_label: "${{ steps.current-time.outputs.time }}"
        deployment_package: deploy.zip

    - name: Deployed!
      run: echo App deployed to ELB
